### ISSUE TITLE
“我的”页面底部有一个滚动广告没有去掉

### ISSUE THREAD

**Issue by Monarchdos** [duzhaokun123/FuckCainiao#3]
“我的”页面底部有一个滚动广告没有去掉
![Screenshot_2023-09-23-10-18-14-00_ab151674a30e066f032806c4762e5bc5](https://github.com/duzhaokun123/FuckCainiao/assets/42509185/6f936602-40fc-4dd5-ab57-635861dedebe)

**Comment by duzhaokun123** [comment]
但是几乎不看我的页面 问题不大
