### ISSUE TITLE
增加捐赠入口

### ISSUE THREAD

**Issue by Oldcucumber** [duzhaokun123/FuckCainiao#5]
你好，我想打钱）

**Comment by duzhaokun123** [comment]
得加界面 好麻烦啊

**Comment by Oldcucumber** [comment]
还真是，不过可以在readme里面加个码）

**Comment by duzhaokun123** [comment]
https://github.com/duzhaokun123/FuckCainiao/commit/fe09c572aeac9aa94abeb1d1b3813659bdd6838c
